include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: mqtt
    STATUS_CHECK_DELAY: 60
    DD_TRAEFIK_SUBDOMAIN: ${CI_PROJECT_NAME}
  environment:
    url: https://${DD_TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}
