include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: mqtt
    SERVICES_TO_CHECK: mqtt_vmq-redis mqtt_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 60
