version: '3.5'

services:
  vernemq:
    image: ${VERNEMQ_IMAGE_NAME:-erlio/docker-vernemq}:${VERNEMQ_IMAGE_TAG:-latest}
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS:
      DOCKER_IP_ADDRESS:
      DOCKER_VERNEMQ_DISTRIBUTED_COOKIE:
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD:
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL:
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY:
      DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED:
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST:
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT:
    networks:
      vernemq-net:
      metric-net:
    ports:
      - target: ${MQTT_PORT}
        published: ${EXTERNAL_MQTT_PORT}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${SECURE_MQTT_PORT}
        published: ${EXTERNAL_SECURE_MQTT_PORT}
        protocol: tcp
        mode: ${PORT_MODE}
    volumes:
      - vernemq-data-vol:/vernemq/data
      - vernemq-etc-vol:/vernemq/etc
      - vernemq-log-vol:/vernemq/log
    deploy:
      mode: replicated
      replicas: ${VERNEMQ_REPLICAS:-1}
      restart_policy:
        delay: ${VERNEMQ_RESTART_DELAY:-10s}
      update_config:
        delay: ${VERNEMQ_UPDATE_DELAY:-1m}
      labels:
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN:-vernemq}.${PUBLIC_HOSTNAME};AddPrefix:/status
        traefik.backend: vernemq
        traefik.port: '${HTTP_PORT}'
      resources:
        limits:
          cpus: '${VERNEMQ_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${VERNEMQ_RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${VERNEMQ_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${VERNEMQ_RESOURCES_RESERVATIONS_MEMORY:-80M}

  vmq-redis:
    image: ${REDIS_IMAGE_NAME:-redis}:${REDIS_IMAGE_TAG:-latest}
    command: redis-server --appendonly yes
    networks:
      vernemq-net:
    volumes:
      - redis-data-vol:/data
    deploy:
      mode: replicated
      replicas: ${REDIS_REPLICAS:-1}
      restart_policy:
        delay: ${REDIS_RESTART_DELAY:-5s}
      update_config:
        delay: ${REDIS_UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${REDIS_RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${REDIS_RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${REDIS_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${REDIS_RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  vernemq-net:
    name: ${VERNEMQ_NET_NAME:-vernemq-net}
    driver: ${VERNEMQ_NET_DRIVER:-overlay}
    attachable: ${VERNEMQ_NET_ATTACHABLE:-false}

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

volumes:
  vernemq-data-vol:
    name: ${VERNEMQ_DATA_VOL_NAME:-vernemq-data-vol}

  vernemq-etc-vol:
    name: ${VERNEMQ_ETC_VOL_NAME:-vernemq-etc-vol}

  vernemq-log-vol:
    name: ${VERNEMQ_LOG_VOL_NAME:-vernemq-log-vol}
