version: '3.5'

volumes:
  vernemq-data-vol:
    name: ${VERNEMQ_DATA_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTIONS}
      device: ${VERNEMQ_DATA_VOL_DEVICE}

  vernemq-conf-vol:
    name: ${VERNEMQ_CONF_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTIONS}
      device: ${VERNEMQ_CONF_VOL_DEVICE}

  redis-data-vol:
    name: ${REDIS_DATA_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTIONS}
      device: ${REDIS_DATA_VOL_DEVICE}
