version: '3.5'

services:
  vernemq:
    image: erlio/docker-vernemq:${IMAGE_TAG:-latest}
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      - DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT
      - DOCKER_IP_ADDRESS
      - DOCKER_VERNEMQ_DISTRIBUTED_COOKIE
      - DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD
      - DOCKER_VERNEMQ_PLUGINS__VMQ_ACL
      - DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT
    networks:
      - vernemq-net
      - traefik-net
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 8883
        published: 8883
        protocol: tcp
        mode: host
    volumes:
      - vernemq-data-vol:/vernemq/data
      - vernemq-etc-vol:/vernemq/etc
      - vernemq-log-vol:/vernemq/log
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.websocket.frontend.rule: Host:${SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.metrics.frontend.auth.basic.users: ${UI_AUTH}
        traefik.metrics.frontend.rule: Host:${SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/metrics
        traefik.backend: vernemq
        traefik.websocket.port: '8080'
        traefik.metrics.port: '8888'
      restart_policy:
        delay: 10s
        window: 2m
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          memory: 205M

  vmq-redis:
    image: redis:${REDIS_IMAGE_TAG:-latest}
    command: redis-server --appendonly yes
    networks:
      - vernemq-net
    volumes:
      - redis-data-vol:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          memory: 32M

networks:
  vernemq-net:
    name: ${VERNEMQ_NET_NAME:-vernemq-net}
    driver: overlay
    attachable: ${VERNEMQ_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  vernemq-data-vol:
    name: ${VERNEMQ_DATA_VOL_NAME:-vernemq-data-vol}

  vernemq-etc-vol:
    name: ${VERNEMQ_ETC_VOL_NAME:-vernemq-etc-vol}

  vernemq-log-vol:
    name: ${VERNEMQ_LOG_VOL_NAME:-vernemq-log-vol}
