version: '3.5'

services:
  vernemq:
    deploy:
      placement:
        constraints:
          - node.role == worker

  vmq-redis:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  redis-data-vol:
    name: ${REDIS_DATA_VOL_NAME:-vernemq-redis-data-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
